### PR TITLE
#169250460 Document Existing API endpoints using swagger 

### PR DESCRIPTION
**Pull request by thoth-ky**
This PR implements API documentation by the use of [rswag](https://github.com/rswag/rswag) gem. To access the documentation after starting the server, go to`/api-docs`. 

CHORES:
- README is updated with necessary info to setup and access the API documentation
- Introduces use of Swagger for integration testing
- Moves all current existing API response messages to use the [I18n locales](https://guides.rubyonrails.org/i18n.html)

### CODE REVIEW

**Comment by gloriaodipo** [comment]
Good job! One thing though, could you please provide a step-by-step guide on how to document future API endpoints.

**Review by gloriaodipo — CHANGES_REQUESTED** [review]
Good job! One thing though, could you please provide a step-by-step guide on how to document future API endpoints.

**Comment by thoth-ky** [comment]
@gloriaodipo , changes requested have been added to the CONTRIBUTING.md file and a link to it left in the README

**Review by gloriaodipo — APPROVED** [review]
LGTM!

**Pull request merged**
